"""add_report_generated_at_to_test_plans

Revision ID: da4849e2104c
Revises: 456826c94be8
Create Date: 2026-03-04 10:42:50.973508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'da4849e2104c'
down_revision: Union[str, None] = '456826c94be8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_plans', sa.Column('report_generated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_plans', 'report_generated_at')
    # ### end Alembic commands ###
